const eci = (ref: string) => {
  const c = ref.split("");
  return `https://www.elcorteingles.es/imagenes/${c[0]}/${c[1]}/${c[2]}/${c[3]}/${c[4]}/${c[5]}/${c[6]}/${ref}.jpg`;
};

export type Product = {
  id: string;
  ref: string;
  brand: string;
  name: string;
  shortName: string;
  category: string;
  price: number;
  oldPrice: number;
  img: string;
  images?: string[];
  badge?: string;
  color?: string;
  description: string;
  features: string[];
  specs: { label: string; value: string }[];
  eciUrl: string;
};

export const products: Product[] = [
  {
    id: "lg-55qned85a6c",
    ref: "A55484387",
    brand: "LG",
    name: "TV QNED evo MiniLED AI 139cm (55\") LG 55QNED85A6C 4K Smart TV",
    shortName: "LG 55QNED85A6C TV QNED MiniLED 55\"",
    category: "Televisores",
    price: 499,
    oldPrice: 999,
    img: "/assets/products/lg-55qned85-1.png",
    images: [
      "/assets/products/lg-55qned85-1.png",
      "/assets/products/lg-55qned85-2.png",
      "/assets/products/lg-55qned85-3.png",
      "/assets/products/lg-55qned85-4.png",
      "/assets/products/lg-55qned85-5.png",
    ],
    badge: "SÚPER",
    color: "Negro",
    description: "Experimenta el MiniLED de LG con tecnología QNED evo AI. 2.040 zonas de control de luz para una precisión y nitidez inigualables. Procesador AI α8 Gen3 con inteligencia artificial para una imagen perfecta.",
    features: ["MiniLED con 2.040 zonas", "Procesador AI α8 Gen3", "4K UHD 120Hz", "Smart TV webOS 24", "HDR10 / Dolby Vision IQ", "Peana ajustable en altura"],
    specs: [
      { label: "Tamaño", value: "55\" (139 cm)" },
      { label: "Resolución", value: "4K UHD (3840×2160)" },
      { label: "Tecnología", value: "QNED evo MiniLED AI" },
      { label: "Frecuencia", value: "120 Hz" },
      { label: "Sistema operativo", value: "webOS 24" },
      { label: "Conectividad", value: "Wi-Fi, Bluetooth, 4×HDMI, 2×USB" },
      { label: "HDR", value: "HDR10, Dolby Vision IQ, HLG" },
      { label: "Energía", value: "Clase E" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A55484387-8806096349069-pr-tv-qned-evo-miniled-ai-139cm-55-lg-55qned85a6c-4k-smart-tv-negro/",
  },
  {
    id: "dyson-v15-detect",
    ref: "A48432162",
    brand: "Dyson",
    name: "Aspirador de escoba recargable Dyson V15 Detect Absolute",
    shortName: "Dyson V15 Detect Absolute",
    category: "Electrodomésticos",
    price: 599,
    oldPrice: 799,
    img: "/assets/products/dyson-v15-1.png",
    images: [
      "/assets/products/dyson-v15-1.png",
      "/assets/products/dyson-v15-2.png",
      "/assets/products/dyson-v15-3.png",
      "/assets/products/dyson-v15-4.png",
    ],
    badge: "SÚPER",
    color: "Amarillo/Nickel",
    description: "El aspirador más potente de Dyson. El sensor láser revela el polvo invisible al ojo humano. La pantalla LCD muestra en tiempo real el tamaño y la cantidad de partículas detectadas.",
    features: ["Potencia de aspiración de 240 AW", "Sensor láser de polvo", "Pantalla LCD inteligente", "Hasta 60 min de autonomía", "5 accesorios incluidos", "Filtro de 5 etapas"],
    specs: [
      { label: "Potencia", value: "240 AW" },
      { label: "Autonomía", value: "Hasta 60 min" },
      { label: "Capacidad", value: "0,77 L" },
      { label: "Filtración", value: "5 etapas, HEPA" },
      { label: "Peso", value: "3,1 kg" },
      { label: "Accesorios", value: "5 incluidos" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A48432162-5025155081754-pr-aspirador-de-escoba-recargable-dyson-v15-detect-absolute/",
  },
  {
    id: "hp-omnibook3-16",
    ref: "A57956043",
    brand: "HP",
    name: "Portátil HP OmniBook 3 16-by0000ns Ryzen 5 40, 16GB, 512GB SSD, 16\", W11",
    shortName: "HP OmniBook 3 16\" Ryzen 5 16GB",
    category: "Informática",
    price: 649,
    oldPrice: 849,
    img: "/assets/products/hp-omnibook3-1.png",
    images: [
      "/assets/products/hp-omnibook3-1.png",
      "/assets/products/hp-omnibook3-2.png",
      "/assets/products/hp-omnibook3-3.png",
      "/assets/products/hp-omnibook3-4.png",
    ],
    badge: "SÚPER",
    color: "Azul",
    description: "Rendimiento excepcional con procesador AMD Ryzen 5 de última generación. Pantalla de 16\" con resolución Full HD+ y batería de larga duración. Perfecto para trabajo y entretenimiento.",
    features: ["Procesador AMD Ryzen 5 40", "16 GB RAM DDR5", "512 GB SSD NVMe", "Pantalla 16\" Full HD+", "Windows 11 Home", "Autonomía 12+ horas"],
    specs: [
      { label: "Procesador", value: "AMD Ryzen 5 40 Series" },
      { label: "RAM", value: "16 GB DDR5" },
      { label: "Almacenamiento", value: "512 GB SSD NVMe" },
      { label: "Pantalla", value: "16\" Full HD+ IPS" },
      { label: "Sistema operativo", value: "Windows 11 Home" },
      { label: "Batería", value: "Hasta 12 horas" },
      { label: "Color", value: "Azul" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A57956043-0199896111959-pr-portatil-hp-omnibook-3-16-by0000ns-ryzen-5-40-16gb-512gb-ssd-16-w11-sin-cargador-azul/",
  },
  {
    id: "lg-frigorifico-combi",
    ref: "A200792455",
    brand: "LG",
    name: "Frigorífico Combi LG Serie 500 Total No Frost Door Cooling+ GBBS524CSW Blanco",
    shortName: "LG GBBS524CSW Frigorífico Combi Blanco",
    category: "Electrodomésticos",
    price: 799,
    oldPrice: 1099,
    img: "/assets/products/lg-gbbs524-1.png",
    images: [
      "/assets/products/lg-gbbs524-1.png",
      "/assets/products/lg-gbbs524-2.png",
      "/assets/products/lg-gbbs524-3.png",
      "/assets/products/lg-gbbs524-4.png",
      "/assets/products/lg-gbbs524-5.png",
    ],
    badge: "SÚPER",
    color: "Blanco",
    description: "Frigorífico combi LG con tecnología Total No Frost y Door Cooling+. Distribución uniforme del aire frío para mantener los alimentos en perfecto estado más tiempo.",
    features: ["Total No Frost", "Door Cooling+", "Capacidad total 384L", "Linear Cooling", "Wi-Fi SmartThinQ", "Eficiencia energética E"],
    specs: [
      { label: "Capacidad total", value: "384 L" },
      { label: "Zona frigo", value: "277 L" },
      { label: "Zona congelador", value: "107 L" },
      { label: "Tecnología", value: "Total No Frost" },
      { label: "Dimensiones", value: "203 × 59,5 × 68,2 cm" },
      { label: "Eficiencia", value: "Clase E" },
      { label: "Ruido", value: "36 dB" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A200792455-8806096627099-pr-frigorifico-combi-lg-serie-500-total-no-frost-door-cooling--gbbs524csw-blanco/",
  },
  {
    id: "xiaomi-redmi-note15-pro",
    ref: "A200383452",
    brand: "Xiaomi",
    name: "Xiaomi Redmi Note 15 Pro+ 5G 8GB 256GB Móvil libre Negro",
    shortName: "Xiaomi Redmi Note 15 Pro+ 5G 8/256GB",
    category: "Móviles",
    price: 279,
    oldPrice: 379,
    img: eci("A200383452"),
    badge: "SÚPER",
    color: "Negro",
    description: "Rendimiento top con Snapdragon 7s Gen 3, cámara de 200 MP y batería de 5.500 mAh con carga rápida de 90W. El mejor smartphone de la gama media.",
    features: ["Snapdragon 7s Gen 3", "Cámara principal 200 MP", "Batería 5.500 mAh", "Carga rápida 90W", "Pantalla AMOLED 6,67\" 144Hz", "5G nativo"],
    specs: [
      { label: "Procesador", value: "Snapdragon 7s Gen 3" },
      { label: "RAM", value: "8 GB" },
      { label: "Almacenamiento", value: "256 GB" },
      { label: "Pantalla", value: "6,67\" AMOLED 144Hz" },
      { label: "Cámara", value: "200 + 8 + 2 MP" },
      { label: "Batería", value: "5.500 mAh / 90W" },
      { label: "Conectividad", value: "5G, Wi-Fi 6, NFC" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A200383452-6932554490133-pr-xiaomi-redmi-note-15-pro-plus-5g-8gb-256-gb-movil-libre-negro-256-gb-8-gb-ram/",
  },
  {
    id: "aeg-lavadora-lfe6",
    ref: "A57223580",
    brand: "AEG",
    name: "Lavadora AEG 10,5 kg 1400 rpm LFE6G54H4B Blanco",
    shortName: "AEG LFE6G54H4B Lavadora 10,5 kg",
    category: "Electrodomésticos",
    price: 499,
    oldPrice: 699,
    img: "/assets/products/aeg-lfe6g54-1.png",
    images: [
      "/assets/products/aeg-lfe6g54-1.png",
      "/assets/products/aeg-lfe6g54-2.png",
      "/assets/products/aeg-lfe6g54-3.png",
      "/assets/products/aeg-lfe6g54-4.png",
    ],
    badge: "SÚPER",
    color: "Blanco",
    description: "Lavadora AEG con tecnología ProSteam para eliminar el 99,9% de los alérgenos. OKOMix mezcla el agua y el detergente antes de que entren en contacto con la ropa.",
    features: ["10,5 kg de capacidad", "1400 rpm", "ProSteam anti-alérgenos", "OKOMix tecnología", "Clase A energética", "Pantalla LED"],
    specs: [
      { label: "Capacidad", value: "10,5 kg" },
      { label: "Velocidad máx.", value: "1400 rpm" },
      { label: "Eficiencia energética", value: "Clase A" },
      { label: "Eficiencia centrifugado", value: "Clase A" },
      { label: "Consumo", value: "52 kWh/100 ciclos" },
      { label: "Ruido", value: "47 dB (lavado)" },
      { label: "Dimensiones", value: "85 × 60 × 65 cm" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A57223580-7333394145587-pr-lavadora-aeg-105-kg-1400-rpm-lfe6g54h4b-blanco/",
  },
  {
    id: "apple-airpods-pro3",
    ref: "A56790285",
    brand: "Apple",
    name: "Auriculares de botón Apple AirPods Pro 3 Blanco",
    shortName: "Apple AirPods Pro 3",
    category: "Audio",
    price: 249,
    oldPrice: 299,
    img: "/assets/products/airpods-pro3-1.png",
    images: [
      "/assets/products/airpods-pro3-1.png",
      "/assets/products/airpods-pro3-2.png",
      "/assets/products/airpods-pro3-3.png",
      "/assets/products/airpods-pro3-4.png",
      "/assets/products/airpods-pro3-5.png",
    ],
    badge: "NUEVO",
    color: "Blanco",
    description: "La tercera generación de AirPods Pro con cancelación activa de ruido rediseñada, audio adaptativo y chip H2. La mejor experiencia de audio inalámbrico de Apple.",
    features: ["Cancelación activa de ruido H2", "Audio Adaptativo", "Modo Transparencia", "Hasta 6h batería (30h con estuche)", "Resistencia IP54", "Audio espacial personalizado"],
    specs: [
      { label: "Chip", value: "Apple H2" },
      { label: "Batería auriculares", value: "Hasta 6 horas" },
      { label: "Batería total", value: "Hasta 30 horas" },
      { label: "Cancelación de ruido", value: "Sí (ANC activo)" },
      { label: "Resistencia", value: "IP54" },
      { label: "Conectividad", value: "Bluetooth 5.3" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A56790285-0195950543742-pr-auriculares-de-boton-apple-airpods-pro-3-blanco/",
  },
  {
    id: "daitsu-split-ds9klf",
    ref: "A54700253",
    brand: "Daitsu",
    name: "Aire acondicionado Split 1×1 Daitsu Inverter con 2.235 frig/h y WiFi Artic Lite DS-9KLF Blanco",
    shortName: "Daitsu DS-9KLF Split Inverter WiFi 2.235 frig/h",
    category: "Climatización",
    price: 399,
    oldPrice: 599,
    img: "/assets/products/daitsu-split-1.png",
    images: [
      "/assets/products/daitsu-split-1.png",
      "/assets/products/daitsu-split-2.png",
      "/assets/products/daitsu-split-3.png",
      "/assets/products/daitsu-split-4.png",
    ],
    badge: "SÚPER",
    color: "Blanco",
    description: "Aire acondicionado split inverter con WiFi integrado. Control desde tu smartphone con la app Daitsu. Alta eficiencia energética y funcionamiento silencioso.",
    features: ["Inverter WiFi integrado", "2.235 frig/h frío", "2.322 kcal/h calor", "Control app Daitsu", "Modo Silencioso", "Eficiencia A++/A+"],
    specs: [
      { label: "Potencia frío", value: "2.235 frig/h (2.600 W)" },
      { label: "Potencia calor", value: "2.322 kcal/h" },
      { label: "SEER", value: "A++" },
      { label: "SCOP", value: "A+" },
      { label: "WiFi", value: "Sí (app Daitsu)" },
      { label: "Ruido int.", value: "22 dB(A)" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A54700253-8432884645350-pr-aire-acondicionado-split-1x1-daitsu-inverter-con-2235-frigh-y-2322-kcalh-wifi-artic-lite-ds-9klf-blanco/",
  },
  {
    id: "bosch-lavavajillas-smv4",
    ref: "A52601354",
    brand: "Bosch",
    name: "Lavavajillas integrable Bosch 14 servicios bandeja para cubiertos 60 cm SMV4ECX28E",
    shortName: "Bosch SMV4ECX28E Lavavajillas Integrable 14 servicios",
    category: "Electrodomésticos",
    price: 699,
    oldPrice: 899,
    img: "/assets/products/bosch-lavavajillas-1.png",
    images: [
      "/assets/products/bosch-lavavajillas-1.png",
      "/assets/products/bosch-lavavajillas-2.png",
      "/assets/products/bosch-lavavajillas-3.png",
      "/assets/products/bosch-lavavajillas-4.png",
      "/assets/products/bosch-lavavajillas-5.png",
    ],
    badge: "SÚPER",
    color: "Inox",
    description: "Lavavajillas totalmente integrable Bosch con capacidad para 14 cubiertos y bandeja extraíble para cubiertos en el tercer cajón. Silencio de 44 dB.",
    features: ["14 servicios de capacidad", "Tercer cajón para cubiertos", "44 dB silencioso", "EfficientDry", "PerfectDry", "6 programas de lavado"],
    specs: [
      { label: "Capacidad", value: "14 servicios" },
      { label: "Ruido", value: "44 dB" },
      { label: "Eficiencia energética", value: "Clase C" },
      { label: "Eficiencia secado", value: "Clase A" },
      { label: "Anchura", value: "60 cm" },
      { label: "Programas", value: "6" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A52601354-4242005484386-pr-lavavajillas-integrable-bosch-14-servicios-bandeja-para-cubiertos-60-cm-smv4ecx28e/",
  },
  {
    id: "daitsu-portatil-apd12",
    ref: "A200472958",
    brand: "Daitsu",
    name: "Aire acondicionado portátil Daitsu con 3.000 frig/h Aeris Dual APD-12FCXB Blanco",
    shortName: "Daitsu APD-12FCXB Portátil 3.000 frig/h",
    category: "Climatización",
    price: 359,
    oldPrice: 559,
    img: "/assets/products/daitsu-portatil-1.png",
    images: [
      "/assets/products/daitsu-portatil-1.png",
      "/assets/products/daitsu-portatil-2.png",
      "/assets/products/daitsu-portatil-3.png",
      "/assets/products/daitsu-portatil-4.png",
    ],
    badge: "SÚPER",
    color: "Blanco",
    description: "Aire acondicionado portátil con doble manguera para mayor eficiencia. Sin instalación permanente. Ideal para cualquier habitación del hogar.",
    features: ["3.000 frig/h de potencia", "Doble manguera Aeris Dual", "Sin instalación fija", "Función calor", "Control remoto", "Temporizador 24h"],
    specs: [
      { label: "Potencia frío", value: "3.000 frig/h (3.500 W)" },
      { label: "Tipo", value: "Portátil doble manguera" },
      { label: "EER", value: "2,62" },
      { label: "Ruido", value: "56 dB(A)" },
      { label: "Dimensiones", value: "40 × 39,5 × 76,5 cm" },
      { label: "Peso", value: "33 kg" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A200472958-8432884649808-pr-aire-acondicionado-portatil-daitsu-con-3000-frigh-2750-kcalh-aeris-dual-apd-12fcxb-blanco/",
  },
  {
    id: "bosch-frigorifico-kgn392",
    ref: "A55025496",
    brand: "Bosch",
    name: "Frigorífico Combi Bosch Total No Frost 203 × 60cm KGN392LAG Acero antihuellas",
    shortName: "Bosch KGN392LAG Frigorífico Combi Acero",
    category: "Electrodomésticos",
    price: 799,
    oldPrice: 1099,
    img: eci("A55025496"),
    badge: "SÚPER",
    color: "Acero antihuellas",
    description: "Frigorífico combi Bosch con Total No Frost para olvidarte de descongelar. Acabado acero antihuellas elegante y duradero. Alarma de puerta y filtro MultiAirFlow.",
    features: ["Total No Frost", "Acero antihuellas", "Alarma puerta abierta", "MultiAirFlow", "FreshSense sensor", "VitaFresh 90 días"],
    specs: [
      { label: "Capacidad total", value: "337 L" },
      { label: "Zona frigo", value: "236 L" },
      { label: "Zona congelador", value: "101 L" },
      { label: "Dimensiones", value: "203 × 60 × 66 cm" },
      { label: "Eficiencia", value: "Clase C" },
      { label: "Ruido", value: "38 dB" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A55025496-4242005502493-pr-frigorifico-combi-bosch-total-no-frost-203-x-60cm-kgn392lag-acero-antihuellas/",
  },
  {
    id: "dyson-cool-am07",
    ref: "A12209298",
    brand: "Dyson",
    name: "Ventilador de torre Dyson Cool™ AM07 con tecnología Air Multiplier™ Blanco",
    shortName: "Dyson Cool AM07 Ventilador de Torre",
    category: "Climatización",
    price: 279,
    oldPrice: 349,
    img: eci("A12209298"),
    badge: "SÚPER",
    color: "Blanco/Plata",
    description: "Ventilador de torre sin aspas Dyson con tecnología Air Multiplier™. Flujo de aire suave y uniforme 15 veces más potente que un ventilador convencional sin aspas peligrosas.",
    features: ["Sin aspas Air Multiplier", "10 velocidades de aire", "Oscilación 70°", "Temporizador hasta 9h", "Mando a distancia", "Silencioso 44 dB"],
    specs: [
      { label: "Tecnología", value: "Air Multiplier™" },
      { label: "Velocidades", value: "10" },
      { label: "Oscilación", value: "70°" },
      { label: "Temporizador", value: "Hasta 9 horas" },
      { label: "Ruido", value: "44 dB" },
      { label: "Dimensiones", value: "18,8 × 18,8 × 102,5 cm" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A12209298-5025155017838-pr-ventilador-de-torre-dyson-cool-am07-con-tecnologia-air-multiplier--blanco-blanco/",
  },
  {
    id: "huawei-watch-fit4",
    ref: "A55590368",
    brand: "Huawei",
    name: "Huawei Watch Fit 4 Negro Smartwatch",
    shortName: "Huawei Watch Fit 4 Negro",
    category: "Wearables",
    price: 99,
    oldPrice: 149,
    img: eci("A55590368"),
    badge: "NUEVO",
    color: "Negro",
    description: "Smartwatch deportivo ultraligero con pantalla AMOLED de 1,82\". GPS dual integrado, monitorización cardíaca continua y hasta 10 días de autonomía.",
    features: ["Pantalla AMOLED 1,82\"", "GPS dual integrado", "10 días autonomía", "Monitorización cardíaca 24/7", "SpO2 y estrés", "Más de 100 modos deporte"],
    specs: [
      { label: "Pantalla", value: "1,82\" AMOLED 480×408 px" },
      { label: "Autonomía", value: "Hasta 10 días" },
      { label: "GPS", value: "Dual (GPS + GLONASS)" },
      { label: "Resistencia agua", value: "5 ATM" },
      { label: "Sensores", value: "FC, SpO2, acelerómetro, giroscopio" },
      { label: "Peso", value: "26 g" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A55590368-6942103155000-pr-huawei-watch-fit-4-negro-smartwatch-negro/",
  },
  {
    id: "samsung-tv-85-neo-qled",
    ref: "A55550877",
    brand: "Samsung",
    name: "TV Neo QLED Mini LED 214cm (85\") Samsung TQ85QN74FATXXC 4K AI Upscaling Pro Smart TV",
    shortName: "Samsung 85\" Neo QLED 4K AI Smart TV",
    category: "Televisores",
    price: 1299,
    oldPrice: 1799,
    img: eci("A55550877"),
    badge: "SÚPER",
    color: "Negro",
    description: "Televisor de 85\" Neo QLED con tecnología MiniLED y procesador Neural Quantum 4K Pro. AI Upscaling Pro para una imagen perfecta y Dolby Atmos para un sonido envolvente.",
    features: ["85\" pantalla gigante", "Neo QLED MiniLED", "AI Upscaling Pro Neural Quantum", "4K 120Hz", "Dolby Atmos", "Smart TV Tizen"],
    specs: [
      { label: "Tamaño", value: "85\" (214 cm)" },
      { label: "Resolución", value: "4K UHD (3840×2160)" },
      { label: "Tecnología", value: "Neo QLED MiniLED" },
      { label: "Frecuencia", value: "120 Hz" },
      { label: "HDR", value: "HDR10+, HLG" },
      { label: "Sistema operativo", value: "Tizen" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A55550877-8806097070405-pr-tv-neo-qled-mini-led-214cm-85-samsung-tq85qn74fatxxc-4k-ai-upscaling-pro-con-inteligencia-artificial-smart-tv-negro/",
  },
  {
    id: "samsung-galaxy-tab-a9",
    ref: "A55790219",
    brand: "Samsung",
    name: "Tablet Samsung Galaxy Tab A9+ Wi-Fi 8GB 256GB Gris",
    shortName: "Samsung Galaxy Tab A9+ 8/256GB Wi-Fi Gris",
    category: "Tablets",
    price: 229,
    oldPrice: 349,
    img: eci("A55790219"),
    badge: "SÚPER",
    color: "Gris",
    description: "Tablet Samsung con pantalla LCD de 11\" Full HD+ y altavoces cuádruples con Dolby Atmos. Perfecta para entretenimiento, estudio y trabajo.",
    features: ["Pantalla 11\" Full HD+ 90Hz", "Altavoces quad Dolby Atmos", "8 GB RAM / 256 GB", "Batería 7.040 mAh", "WiFi 6", "DeX mode"],
    specs: [
      { label: "Pantalla", value: "11\" LCD Full HD+ 90Hz" },
      { label: "Procesador", value: "Snapdragon 695" },
      { label: "RAM", value: "8 GB" },
      { label: "Almacenamiento", value: "256 GB" },
      { label: "Batería", value: "7.040 mAh" },
      { label: "Sistema operativo", value: "Android 14 / One UI" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A55790219-8806097462835-pr-tablet-samsung-galaxy-tab-a9-wi-fi-8gb-256gb-gris-256-gb-8-gb-ram/",
  },
  {
    id: "ps5-gran-turismo-ghost",
    ref: "A200916152",
    brand: "Sony PlayStation",
    name: "Pack Consola PlayStation 5 + Gran Turismo 7 + Ghost of Yotei",
    shortName: "PS5 Pack Gran Turismo 7 + Ghost of Yotei",
    category: "Videojuegos",
    price: 649,
    oldPrice: 769,
    img: eci("A200916152"),
    badge: "PACK",
    color: "Blanco",
    description: "La consola de nueva generación de Sony con dos juegos exclusivos: Gran Turismo 7, la simulación de conducción definitiva, y Ghost of Yotei, la épica aventura de acción de mundo abierto.",
    features: ["PS5 consola Digital o Disc", "Gran Turismo 7 incluido", "Ghost of Yotei incluido", "SSD ultrarrápido 825 GB", "Ray Tracing nativo", "DualSense con haptics"],
    specs: [
      { label: "Procesador", value: "AMD Zen 2 8 núcleos 3,5 GHz" },
      { label: "GPU", value: "AMD RDNA 2 10,28 TFLOPS" },
      { label: "Almacenamiento", value: "825 GB SSD" },
      { label: "Resolución", value: "Hasta 8K, 120fps" },
      { label: "Audio", value: "3D Audio Tempest" },
      { label: "Juegos incluidos", value: "Gran Turismo 7 + Ghost of Yotei" },
    ],
    eciUrl: "https://www.elcorteingles.es/videojuegos/A200916152-pack-consola-playstation-5-gran-turismo-7-ghost-of-yotei/",
  },
  {
    id: "apple-iphone-17",
    ref: "A56790273",
    brand: "Apple",
    name: "Apple iPhone 17 256GB Negro Móvil libre",
    shortName: "Apple iPhone 17 256GB Negro",
    category: "Móviles",
    price: 999,
    oldPrice: 1099,
    img: eci("A56790273"),
    badge: "NUEVO",
    color: "Negro",
    description: "El iPhone más avanzado de Apple con chip A19, cámara de 48 MP con zoom óptico 5× y diseño ultradelgado en aluminio de alta calidad. Con Apple Intelligence integrado.",
    features: ["Chip Apple A19", "Cámara 48 MP Fusion + 5× zoom", "Apple Intelligence AI", "Face ID mejorado", "Pantalla Super Retina XDR 6,1\"", "iOS 19"],
    specs: [
      { label: "Chip", value: "Apple A19 Bionic" },
      { label: "Pantalla", value: "6,1\" Super Retina XDR" },
      { label: "Cámara principal", value: "48 MP" },
      { label: "Almacenamiento", value: "256 GB" },
      { label: "Batería", value: "Hasta 22 h vídeo" },
      { label: "Conectividad", value: "5G, Wi-Fi 7, Bluetooth 5.4" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A56790273-0195950643503-pr-apple-iphone-17-256gb-negro-movil-libre-negro-256-gb-8-gb-ram/",
  },
  {
    id: "lg-lavadora-secadora-f4dr",
    ref: "A49218207",
    brand: "LG",
    name: "Lavadora Secadora LG 10 kg lavado 6 kg secado 1400 rpm AI F4DR6010A1W Blanco",
    shortName: "LG F4DR6010A1W Lavadora Secadora 10/6 kg",
    category: "Electrodomésticos",
    price: 799,
    oldPrice: 1099,
    img: eci("A49218207"),
    badge: "SÚPER",
    color: "Blanco",
    description: "Lavadora secadora con Inteligencia Artificial que aprende de tus hábitos de lavado. ThinQ AI ajusta automáticamente el ciclo para cuidar tu ropa al máximo.",
    features: ["10 kg lavado / 6 kg secado", "1400 rpm", "AI DD™ Inteligencia Artificial", "ThinQ WiFi", "Steam Wash & Dry", "Eficiencia A-20%"],
    specs: [
      { label: "Capacidad lavado", value: "10 kg" },
      { label: "Capacidad secado", value: "6 kg" },
      { label: "Velocidad máx.", value: "1400 rpm" },
      { label: "Eficiencia lavado", value: "A-20%" },
      { label: "WiFi", value: "ThinQ SmartThings" },
      { label: "Dimensiones", value: "85 × 60 × 60 cm" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A49218207-8806084122353-pr-lavadora-secadora-lg-10-kg-lavado-6-kg-secado-1400-rpm-inteligencia-artificial-f4dr6010a1w-blanco/",
  },
  {
    id: "nintendo-switch2-minecraft",
    ref: "A200916418",
    brand: "Nintendo",
    name: "Pack Nintendo Switch 2 + Minecraft",
    shortName: "Nintendo Switch 2 + Minecraft",
    category: "Videojuegos",
    price: 449,
    oldPrice: 499,
    img: eci("A200916418"),
    badge: "PACK",
    color: "Negro/Rojo",
    description: "La nueva Nintendo Switch 2 con pantalla LCD de 7,9\" y Joy-Con magnéticos. Incluye Minecraft para disfrutar desde el primer momento.",
    features: ["Pantalla LCD 7,9\" 1080p", "Joy-Con magnéticos", "4K en TV (HDMI 2.0)", "Juego Minecraft incluido", "Retro compatible Switch 1", "Online con Nintendo Switch Online"],
    specs: [
      { label: "Pantalla", value: "7,9\" LCD Full HD" },
      { label: "Procesador", value: "NVIDIA Custom Tegra T239" },
      { label: "RAM", value: "12 GB LPDDR5X" },
      { label: "Almacenamiento", value: "256 GB UFS" },
      { label: "Batería", value: "Hasta 6 horas" },
      { label: "Juego incluido", value: "Minecraft" },
    ],
    eciUrl: "https://www.elcorteingles.es/videojuegos/A200916418-pack-nintendo-switch-2-minecraft/",
  },
  {
    id: "lg-55qned93a6a",
    ref: "A55484369",
    brand: "LG",
    name: "TV QNED evo MiniLED AI 139cm (55\") LG 55QNED93A6A 4K Smart TV Negro",
    shortName: "LG 55QNED93A6A TV QNED MiniLED 55\" 4K",
    category: "Televisores",
    price: 599,
    oldPrice: 1199,
    img: eci("A55484369"),
    badge: "SÚPER",
    color: "Negro",
    description: "TV QNED evo MiniLED de LG con procesador AI α8 Gen3 y 4K a 120Hz. La tecnología MiniLED ofrece el máximo contraste y brillo para una experiencia cinematográfica.",
    features: ["MiniLED QNED evo AI", "Procesador AI α8 Gen3", "4K 120Hz", "Smart TV webOS 24", "Dolby Vision IQ / Atmos", "Game Optimizer"],
    specs: [
      { label: "Tamaño", value: "55\" (139 cm)" },
      { label: "Resolución", value: "4K UHD (3840×2160)" },
      { label: "Frecuencia", value: "120 Hz" },
      { label: "HDR", value: "HDR10, Dolby Vision IQ, HLG" },
      { label: "Sistema operativo", value: "webOS 24" },
      { label: "Conectividad", value: "Wi-Fi 6, BT 5.0, 4×HDMI 2.1, 3×USB" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A55484369-8806096416075-pr-tv-qned-evo-miniled-ai-139cm-55-lg-55qned93a6a-4k-smart-tv-negro/",
  },
  {
    id: "bosch-lavadora-wgg254",
    ref: "A55025505",
    brand: "Bosch",
    name: "Lavadora Bosch 10 kg 1400 rpm Serie 6 WGG254ZEES Blanco",
    shortName: "Bosch WGG254ZEES Lavadora 10 kg Serie 6",
    category: "Electrodomésticos",
    price: 599,
    oldPrice: 799,
    img: eci("A55025505"),
    badge: "SÚPER",
    color: "Blanco",
    description: "Lavadora Bosch Serie 6 con tecnología EcoSilence Drive™ silenciosa y duradera. AntiVibration Design para menor vibración y ruido en el ciclo de centrifugado.",
    features: ["10 kg de capacidad", "1400 rpm", "EcoSilence Drive™ silencioso", "AntiVibration Design", "ActiveWater™ ahorro agua", "15 programas de lavado"],
    specs: [
      { label: "Capacidad", value: "10 kg" },
      { label: "Velocidad máx.", value: "1400 rpm" },
      { label: "Eficiencia energética", value: "Clase A" },
      { label: "Consumo", value: "49 kWh/100 ciclos" },
      { label: "Ruido lavado", value: "47 dB" },
      { label: "Ruido centrifugado", value: "74 dB" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A55025505-4242005502493-pr-lavadora-bosch-10-kg-1400-rpm-serie-6-wgg254zees-blanco/",
  },
  {
    id: "samsung-tv-75-qled",
    ref: "A56017089",
    brand: "Samsung",
    name: "TV QLED 189cm (75\") Samsung TQ75Q7F5AUXXC 4K Vision AI Quantum Dot Smart TV Negro",
    shortName: "Samsung 75\" QLED 4K AI Quantum Dot",
    category: "Televisores",
    price: 799,
    oldPrice: 1199,
    img: eci("A56017089"),
    badge: "SÚPER",
    color: "Negro",
    description: "Televisor de 75\" QLED con tecnología Quantum Dot y Vision AI para una imagen llena de color y precisión. Procesador Neural Quantum 4K AI.",
    features: ["75\" Quantum Dot QLED", "Vision AI Neural Quantum", "4K 120Hz", "Quantum HDR", "Smart TV Tizen", "Multi View"],
    specs: [
      { label: "Tamaño", value: "75\" (189 cm)" },
      { label: "Resolución", value: "4K UHD (3840×2160)" },
      { label: "Tecnología", value: "QLED Quantum Dot" },
      { label: "Frecuencia", value: "120 Hz" },
      { label: "HDR", value: "Quantum HDR, HDR10+" },
      { label: "Sistema operativo", value: "Tizen" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A56017089-8806097124474-pr-tv-qled-189cm-75-samsung-tq75q7f5auxxc-4k-vision-ai-quantum-dot-smart-tv-negro/",
  },
  {
    id: "sony-alpha-7c",
    ref: "A38934031",
    brand: "Sony",
    name: "Sony Alpha 7C Cámara Evil Full Frame cuerpo con sensor CMOS Exmor R 24,2 MP Negro",
    shortName: "Sony Alpha 7C Full Frame 24,2 MP",
    category: "Fotografía",
    price: 1399,
    oldPrice: 1899,
    img: eci("A38934031"),
    badge: "SÚPER",
    color: "Negro",
    description: "La cámara sin espejo full frame más compacta de Sony con sensor Exmor R de 24,2 MP. Estabilización de imagen en 5 ejes y vídeo 4K a 30fps.",
    features: ["Sensor Exmor R 24,2 MP Full Frame", "Estabilización 5 ejes IBIS", "Vídeo 4K 30fps", "Eye AF en tiempo real", "1.000+ disparos/carga", "Cuerpo compacto 509g"],
    specs: [
      { label: "Sensor", value: "Full Frame BSI CMOS 24,2 MP" },
      { label: "ISO", value: "100-51.200" },
      { label: "AF", value: "Eye AF / Real-time Tracking" },
      { label: "Vídeo", value: "4K 30fps / Full HD 120fps" },
      { label: "Estabilización", value: "5 ejes IBIS" },
      { label: "Peso", value: "509 g (sin objetivo)" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A38934031-4548736121652-pr-sony-alpha-7c-camara-evil-full-frame-cuerpo-con-sensor-cmos-exmor-r-de-fotograma-completo-de-242-mp-videos-4kilce7cscec-negro/",
  },
  {
    id: "ninja-creami-nc701",
    ref: "A200483760",
    brand: "Ninja",
    name: "Máquina de helados y elaboraciones frías Ninja CREAMi Scoop & Swirl NC701EU 800W Plata",
    shortName: "Ninja CREAMi NC701EU 800W Heladería",
    category: "Pequeño electrodoméstico",
    price: 179,
    oldPrice: 249,
    img: eci("A200483760"),
    badge: "SÚPER",
    color: "Plata",
    description: "Crea helados, sorbetes, batidos, granizados y más en casa en minutos. 13 programas automáticos y motor de 800W para texturas perfectas.",
    features: ["800W de potencia", "13 programas automáticos", "2 tarrinas de 0,47 L", "Helado, sorbete, batido, granizado", "Función Scoop & Swirl", "Fácil limpieza"],
    specs: [
      { label: "Potencia", value: "800 W" },
      { label: "Programas", value: "13" },
      { label: "Capacidad", value: "2 × 0,47 L" },
      { label: "Peso", value: "6,8 kg" },
      { label: "Dimensiones", value: "16,5 × 36,8 × 41 cm" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A200483760-0622356292306-pr-maquina-de-helados-y-elaboraciones-frias-ninja-creami-scoop-and-swirl-nc701eu-800w-2-litros-y-13-programas-plata/",
  },
  {
    id: "samsung-galaxy-watch7",
    ref: "A52209728",
    brand: "Samsung",
    name: "Samsung Galaxy Watch7 40mm Crema Bluetooth Smartwatch",
    shortName: "Samsung Galaxy Watch7 40mm Crema",
    category: "Wearables",
    price: 179,
    oldPrice: 299,
    img: eci("A52209728"),
    badge: "SÚPER",
    color: "Crema",
    description: "Smartwatch Samsung con chip Exynos W1000 de 3 nm y pantalla sapphire. IA avanzada para análisis de salud: sueño, energía, composición corporal.",
    features: ["Chip Exynos W1000 3nm", "Pantalla sapphire 1,3\" AMOLED", "Análisis composición corporal", "AI Energy Score", "Hasta 40h autonomía", "5 ATM + IP68"],
    specs: [
      { label: "Pantalla", value: "1,3\" AMOLED sapphire 432×432" },
      { label: "Procesador", value: "Exynos W1000 3nm" },
      { label: "RAM / ROM", value: "2 GB / 32 GB" },
      { label: "Batería", value: "300 mAh / Hasta 40 h" },
      { label: "Resistencia", value: "5 ATM + IP68 + MIL-STD-810H" },
      { label: "Conectividad", value: "Bluetooth 5.3, Wi-Fi, NFC" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A52209728-8806095661902-pr-samsung-galaxy-watch7-40mm-crema-bluetooth-smartwatch-crema/",
  },
  {
    id: "delonghi-magnifica-s",
    ref: "A32354696",
    brand: "De'Longhi",
    name: "Cafetera Superautomática De'Longhi Magnifica S ECAM21.112.B con molinillo incorporado Negro",
    shortName: "De'Longhi Magnifica S ECAM21 Superautomática",
    category: "Pequeño electrodoméstico",
    price: 279,
    oldPrice: 449,
    img: eci("A32354696"),
    badge: "SÚPER",
    color: "Negro",
    description: "Cafetera superautomática De'Longhi con molinillo integrado de 13 niveles. Prepare espresso, cappuccino y café largo con solo pulsar un botón desde grano entero.",
    features: ["Molinillo integrado 13 niveles", "15 bar de presión", "1450W de potencia", "Depósito 1,8L", "Cappuccino cremoso", "Sistema de limpieza automático"],
    specs: [
      { label: "Potencia", value: "1450 W" },
      { label: "Presión", value: "15 bar" },
      { label: "Depósito agua", value: "1,8 L" },
      { label: "Deposito granos", value: "250 g" },
      { label: "Molinillo", value: "Integrado 13 niveles" },
      { label: "Dimensiones", value: "24 × 37 × 36 cm" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A32354696-8004399333444-pr-cafetera-superautomatica-delonghi-magnifica-s-ecam21112b-con-molinillo-incorporado-negro/",
  },
  {
    id: "hisense-frigorifico-americano",
    ref: "A53752403",
    brand: "Hisense",
    name: "Frigorífico Americano Hisense Total No Frost WiFi RS818N4IIE1 Inox",
    shortName: "Hisense RS818N4IIE1 Americano No Frost WiFi",
    category: "Electrodomésticos",
    price: 999,
    oldPrice: 1299,
    img: eci("A53752403"),
    badge: "SÚPER",
    color: "Inox",
    description: "Frigorífico americano Hisense de gran capacidad con WiFi integrado y control desde el móvil. Total No Frost y tecnología Multi Airflow para conservar los alimentos.",
    features: ["Americano Total No Frost", "WiFi control remoto", "Gran capacidad 632L", "Multi Airflow 360°", "Dispensador de agua y hielo", "Clase F eficiencia"],
    specs: [
      { label: "Capacidad total", value: "632 L" },
      { label: "Zona frigo", value: "454 L" },
      { label: "Zona congelador", value: "178 L" },
      { label: "Dimensiones", value: "178,6 × 91 × 71 cm" },
      { label: "WiFi", value: "Sí (app hOn)" },
      { label: "Eficiencia", value: "Clase F" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A53752403-6921727073716-pr-frigorifico-americano-hisense-total-no-frost-wifi-rs818n4iie1-inox/",
  },
  {
    id: "samsung-galaxy-s26-ultra",
    ref: "A200297329",
    brand: "Samsung",
    name: "Samsung Galaxy S26 Ultra 12GB 512GB Móvil libre Violeta Cobalto",
    shortName: "Samsung Galaxy S26 Ultra 12/512GB",
    category: "Móviles",
    price: 1449,
    oldPrice: 1699,
    img: eci("A200297329"),
    badge: "NUEVO",
    color: "Violeta Cobalto",
    description: "El smartphone más avanzado de Samsung con Galaxy AI, S Pen integrado, cámara de 200 MP con zoom óptico 10× y pantalla Dynamic AMOLED 2X de 6,9\".",
    features: ["Galaxy AI S25 Ultra", "S Pen integrado", "Cámara 200 MP + 10× zoom", "Pantalla 6,9\" AMOLED 2X 120Hz", "Snapdragon 8 Elite for Galaxy", "Batería 5.000 mAh"],
    specs: [
      { label: "Procesador", value: "Snapdragon 8 Elite for Galaxy" },
      { label: "RAM", value: "12 GB" },
      { label: "Almacenamiento", value: "512 GB" },
      { label: "Pantalla", value: "6,9\" Dynamic AMOLED 2X 120Hz" },
      { label: "Cámara", value: "200 + 50 + 10 + 10 MP" },
      { label: "Batería", value: "5.000 mAh / 45W" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A200297329-8806097827047-pr-samsung-galaxy-s26-ultra-12gb-512gb-movil-libre-violeta-cobalto-512-gb-12-gb-ram/",
  },
  {
    id: "cosori-freidora-twinfry",
    ref: "A52412898",
    brand: "Cosori",
    name: "Freidora de aire Cosori Dual Blaze TwinFry Chef Edition 10 litros con divisor flexible Negro",
    shortName: "Cosori TwinFry Chef 10L Freidora Dual",
    category: "Pequeño electrodoméstico",
    price: 199,
    oldPrice: 249,
    img: eci("A52412898"),
    badge: "SÚPER",
    color: "Negro",
    description: "Freidora de aire dual de 10 litros con divisor flexible para cocinar dos platos diferentes a la vez. Tecnología de calor superior e inferior para resultados perfectos.",
    features: ["10L capacidad dual", "Divisor flexible desmontable", "Sin precalentamiento necesario", "12 funciones preajustadas", "App Cosori control", "85% menos grasa"],
    specs: [
      { label: "Capacidad", value: "10 L (2 × 5 L)" },
      { label: "Potencia", value: "1800 W" },
      { label: "Temperatura", value: "75-230°C" },
      { label: "Funciones", value: "12 programas" },
      { label: "Conectividad", value: "App Cosori (Wi-Fi)" },
      { label: "Dimensiones", value: "39,5 × 27,3 × 31 cm" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A52412898-0810123673285-pr-freidora-de-aire-cosori-dual-blaze-twinfry-chef-edition-con-capacidad-de-10-litros-y-divisor-flexible-negro/",
  },
  {
    id: "samsung-watch-ultra-2025",
    ref: "A56132790",
    brand: "Samsung",
    name: "Samsung Galaxy Watch Ultra 2025 Azul Smartwatch",
    shortName: "Samsung Galaxy Watch Ultra 2025 Azul",
    category: "Wearables",
    price: 549,
    oldPrice: 699,
    img: "/assets/products/samsung-watch-ultra-2025-1.png",
    images: [
      "/assets/products/samsung-watch-ultra-2025-1.png",
      "/assets/products/samsung-watch-ultra-2025-2.png",
      "/assets/products/samsung-watch-ultra-2025-3.png",
      "/assets/products/samsung-watch-ultra-2025-4.png",
      "/assets/products/samsung-watch-ultra-2025-5.png",
    ],
    badge: "NUEVO",
    color: "Azul",
    description: "El smartwatch más resistente de Samsung con carcasa de titanio y cristal de zafiro. Diseñado para atletas de élite con GPS avanzado y análisis de rendimiento profesional.",
    features: ["Titanio + cristal zafiro", "GPS dual frequency", "Análisis running avanzado", "Hasta 48h autonomía", "10 ATM + MIL-STD-810H", "Monitorización ECG"],
    specs: [
      { label: "Caja", value: "Titanio Grade 4" },
      { label: "Cristal", value: "Safiro" },
      { label: "Pantalla", value: "1,5\" AMOLED 480×480" },
      { label: "Batería", value: "590 mAh / Hasta 48 h" },
      { label: "Resistencia", value: "10 ATM + IP68 + MIL-STD-810H" },
      { label: "GPS", value: "L1 + L5 dual frequency" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A56132790-8806097625254-pr-samsung-galaxy-watch-ultra-2025-azul-smartwatch-azul/",
  },
  {
    id: "nikon-z50ii",
    ref: "A53971671",
    brand: "Nikon",
    name: "Cámara Evil Nikon Z50II con objetivo 16-50mm VR Negro",
    shortName: "Nikon Z50II + Objetivo 16-50mm VR",
    category: "Fotografía",
    price: 999,
    oldPrice: 1249,
    img: "/assets/products/nikon-z50ii-1.png",
    images: [
      "/assets/products/nikon-z50ii-1.png",
      "/assets/products/nikon-z50ii-2.png",
      "/assets/products/nikon-z50ii-3.png",
      "/assets/products/nikon-z50ii-4.png",
    ],
    badge: "SÚPER",
    color: "Negro",
    description: "Cámara sin espejo APS-C Nikon Z50II con sensor de 20,9 MP y procesador EXPEED 7. Incluye objetivo Nikkor Z 16-50mm VR para fotos y vídeos de alta calidad.",
    features: ["Sensor APS-C 20,9 MP", "Procesador EXPEED 7", "Vídeo 4K UHD 30fps", "Objetivo 16-50mm VR incluido", "Eye AF inteligente", "Cuerpo compacto 500g"],
    specs: [
      { label: "Sensor", value: "APS-C CMOS 20,9 MP" },
      { label: "ISO", value: "100-51.200" },
      { label: "AF", value: "Hybrid AF con Eye/Animal detect." },
      { label: "Vídeo", value: "4K UHD 30fps / Full HD 120fps" },
      { label: "Objetivo incluido", value: "Nikkor Z 16-50mm f/3.5-6.3 VR" },
      { label: "Peso cuerpo", value: "500 g" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A53971671-8431016000494-pr-camara-evil-nikon-z50ii-con-objetivo-16-50mm-vr-negro/",
  },
  {
    id: "lg-oled55c5",
    ref: "A55484360",
    brand: "LG",
    name: "TV OLED evo AI C5 139cm (55\") LG OLED55C56LB Smart TV 4K Negro",
    shortName: "LG OLED55C5 EVO AI 55\" 4K",
    category: "Televisores",
    price: 999,
    oldPrice: 1799,
    img: "/assets/products/lg-oled55c5-1.png",
    images: [
      "/assets/products/lg-oled55c5-1.png",
      "/assets/products/lg-oled55c5-2.png",
      "/assets/products/lg-oled55c5-3.png",
      "/assets/products/lg-oled55c5-4.png",
    ],
    badge: "SÚPER",
    color: "Negro",
    description: "El televisor OLED evo más avanzado de LG. Cada píxel emite su propia luz con negro perfecto. Procesador AI α9 Gen8 con inteligencia artificial para imagen y sonido perfectos.",
    features: ["OLED evo pixel autoluminoso", "Procesador AI α9 Gen8", "Negro perfecto y contraste infinito", "4K 144Hz Gaming", "Dolby Vision IQ + Atmos", "Smart TV webOS 25"],
    specs: [
      { label: "Tamaño", value: "55\" (139 cm)" },
      { label: "Resolución", value: "4K UHD (3840×2160)" },
      { label: "Tecnología", value: "OLED evo AI" },
      { label: "Frecuencia", value: "144 Hz" },
      { label: "HDR", value: "HDR10, Dolby Vision IQ, HLG" },
      { label: "Conectividad", value: "Wi-Fi 6E, BT 5.0, 4×HDMI 2.1, 3×USB" },
    ],
    eciUrl: "https://www.elcorteingles.es/electronica/A55484360-8806096361924-pr-tv-oled-evo-ai-c5-139cm-55-lg-oled55c56lb-smart-tv-4k-negro/",
  },
  {
    id: "rowenta-dg9661",
    ref: "A49146363",
    brand: "Rowenta",
    name: "Centro de planchado Rowenta Eco Steam Pro DG9661 con tecnología Microsteam 400 HD Laser Negro/Beige",
    shortName: "Rowenta DG9661 Eco Steam Pro Centro Planchado",
    category: "Pequeño electrodoméstico",
    price: 189,
    oldPrice: 279,
    img: "/assets/products/rowenta-dg9661-1.png",
    images: [
      "/assets/products/rowenta-dg9661-1.png",
      "/assets/products/rowenta-dg9661-2.png",
      "/assets/products/rowenta-dg9661-3.png",
      "/assets/products/rowenta-dg9661-4.png",
      "/assets/products/rowenta-dg9661-5.png",
    ],
    badge: "SÚPER",
    color: "Negro/Beige",
    description: "Centro de planchado Rowenta con suela Microsteam 400 HD Laser y 6,5 bar de presión de vapor. Elimina el 99,9% de gérmenes y arrugas más rápido.",
    features: ["Suela Microsteam 400 HD Laser", "6,5 bar de presión vapor", "Calentamiento en 2 min", "Deposito 1,5L desmontable", "Modo Eco ahorro energía", "Anticalcáreo integrado"],
    specs: [
      { label: "Presión vapor", value: "6,5 bar" },
      { label: "Potencia", value: "2400 W" },
      { label: "Depósito", value: "1,5 L" },
      { label: "Calentamiento", value: "2 minutos" },
      { label: "Suela", value: "Microsteam 400 HD Laser" },
      { label: "Peso plancha", value: "1,1 kg" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A49146363-3121040089514-pr-centro-de-planchado-rowenta-eco-steam-pro-dg9661-con-tecnologia-microsteam-400-hd-3d-laser-negro-beige/",
  },
  {
    id: "samsung-bespoke-rs80f66",
    ref: "A54616089",
    brand: "Samsung",
    name: "Frigorífico Americano Samsung Bespoke AI 178cm Twin Cooling Plus 634L Clase C Inox RS80F66KCTEF",
    shortName: "Samsung Bespoke AI RS80F66 Americano 634L",
    category: "Electrodomésticos",
    price: 1699,
    oldPrice: 2299,
    img: "/assets/products/samsung-bespoke-1.png",
    images: [
      "/assets/products/samsung-bespoke-1.png",
      "/assets/products/samsung-bespoke-2.png",
      "/assets/products/samsung-bespoke-3.png",
      "/assets/products/samsung-bespoke-4.png",
      "/assets/products/samsung-bespoke-5.png",
    ],
    badge: "SÚPER",
    color: "Inox",
    description: "Frigorífico americano Samsung Bespoke AI con la tecnología Twin Cooling Plus™ que mantiene la humedad ideal en cada compartimento. AI Mode ajusta automáticamente la temperatura.",
    features: ["Twin Cooling Plus™", "AI Mode inteligente", "634L gran capacidad", "Pantalla táctil SpaceHub", "Dispensador agua y hielo", "Wi-Fi SmartThings"],
    specs: [
      { label: "Capacidad total", value: "634 L" },
      { label: "Dimensiones", value: "178,5 × 91,2 × 71,6 cm" },
      { label: "Eficiencia", value: "Clase C" },
      { label: "Wi-Fi", value: "SmartThings" },
      { label: "Tecnología", value: "Twin Cooling Plus™" },
      { label: "Ruido", value: "35 dB" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A54616089-8806097164623-pr-frigorifico-americano-samsung-bespoke-ai-178cm-twin-cooling-plus-634l-clase-c-inox-rs80f66kctef-inox/",
  },
  {
    id: "dyson-airstrait",
    ref: "A55088275",
    brand: "Dyson",
    name: "Plancha secador de pelo Dyson Airstrait™ sin placas calientes Ceramic Pink Rose Gold",
    shortName: "Dyson Airstrait™ Ceramic Pink",
    category: "Cuidado personal",
    price: 349,
    oldPrice: 449,
    img: "/assets/products/dyson-airstrait-1.png",
    images: [
      "/assets/products/dyson-airstrait-1.png",
      "/assets/products/dyson-airstrait-2.png",
      "/assets/products/dyson-airstrait-3.png",
      "/assets/products/dyson-airstrait-4.png",
    ],
    badge: "NUEVO",
    color: "Ceramic Pink/Rose Gold",
    description: "La plancha alisadora Dyson que no usa calor extremo sino aire forzado para alisar el cabello sin dañarlo. Dos modos: húmedo (para alisar mojado) y seco (para retoques).",
    features: ["Sin placas calientes de contacto", "Alisa en húmedo y en seco", "Aire fluido supersónico", "Control de temperatura preciso", "Cabezal flexible 90°", "Para todo tipo de cabello"],
    specs: [
      { label: "Tecnología", value: "Air Straightening (sin placas)" },
      { label: "Modos", value: "Wet Dry" },
      { label: "Motor", value: "Dyson digital hyperdymium" },
      { label: "Cable", value: "2,7 m giratorio 360°" },
      { label: "Temperatura", value: "Control preciso" },
      { label: "Color", value: "Ceramic Pink / Rose Gold" },
    ],
    eciUrl: "https://www.elcorteingles.es/electrodomesticos/A55088275-5025155113080-pr-plancha-secador-de-pelo-dyson-airstrait-sin-placas-calientes-ceramic-pink-ceramic-pink-rose-gold/",
  },
];

// Backward-compatible Kit type for checkout
export type Kit = {
  id: string;
  name: string;
  contents: string;
  description: string;
  price: number;
  oldPrice: number;
  img: string;
  badge?: { text: string; colorClass: string };
};

export const kits: Kit[] = products.map((p) => ({
  id: p.id,
  name: p.shortName,
  contents: p.brand,
  description: p.description.slice(0, 120),
  price: p.price,
  oldPrice: p.oldPrice,
  img: p.img,
  badge: p.badge ? { text: p.badge, colorClass: "bg-red-500 text-white" } : undefined,
}));
